services:
  integration_test:
    build: .
    depends_on:
      - redis
      - redisinsight
      - celery_worker
      - orchestrator
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_HOST=db
      - POSTGRES_DB=sagadb
      - POSTGRES_USER=sagauser
      - POSTGRES_PASSWORD=sagapass
      - PYTHONPATH=/app
    command: pytest -vv --full-trace tests/integration/
    volumes:
      - ./app:/app/app:ro
      - ./tests:/app/tests:ro
