services:
  unit_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pytest -vv tests/unit/ -q
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=memory://
      - CELERY_RESULT_BACKEND=cache+memory://
    volumes:
      - ./tests:/app/tests:ro

  lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ruff check .
    environment:
      - PYTHONPATH=/app
      - RUFF_CACHE_DIR=/tmp/.ruff_cache
    volumes:
      - .:/app
      - /tmp:/tmp
