# version: "3.9"
services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_DB=sagadb
      - POSTGRES_USER=sagauser
      - POSTGRES_PASSWORD=sagapass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  celery_worker:
    build: .
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_HOST=db
      - POSTGRES_DB=sagadb
      - POSTGRES_USER=sagauser
      - POSTGRES_PASSWORD=sagapass
    command: celery -A app.celery_app worker --loglevel=info
    healthcheck:
      test: ["CMD", "celery", "-A", "app.celery_app", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  flower:
    image: mher/flower:latest
    depends_on:
      - redis
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  pgdata:
